[workspace]
members = [
    "packages/membrane",
    "contracts/auction",
    "contracts/byte-minter",
    "contracts/car",
    "contracts/cdp",
    "contracts/discount_vault",
    "contracts/governance",
    "contracts/launch",
    "contracts/liq-queue",
    "contracts/liquidity_check",
    "contracts/mars-vault-token",
    "contracts/oracle",
    "contracts/osmosis-proxy",
    "contracts/points-system",
    "contracts/race-engine",
    "contracts/range-bound-lp-vault",
    "contracts/stability-pool",
    "contracts/stability-pool-vault",
    "contracts/stable-earn-vault",
    "contracts/staking",
    "contracts/system_discounts",
    "contracts/tokenfactory",
    "contracts/tournament",
    "contracts/track-manager",
    "contracts/vesting",
    "contracts/vol-earn-vault",
    "contracts/racing-revenue"
]

exclude = [
    "my_scripts", 
    "artifacts", 
    "contracts/cdp/src/testing/*", 
    "contracts/target/*",
    "contracts/managed-market",
    "contracts/market-manager", 
    "contracts/mm-swap",
    "contracts/mm_osmosis_oracle"
]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 'z'
overflow-checks = true
panic = 'abort'
rpath = false

[workspace.dependencies]
base64ct = "=1.7.3"

