[workspace]
members = [
    "packages/membrane",
    "contracts/auction",
    "contracts/cdp",
    "contracts/discount_vault",
    "contracts/governance",
    "contracts/launch",
    "contracts/liq-queue",
    "contracts/ltv_disco",
    "contracts/mars-mirror",
    "contracts/mars-vault-token",
    "contracts/oracle",
    "contracts/points-system",
    "contracts/stable-earn-vault",
    "contracts/staking",
    "contracts/system_discounts",
    "contracts/tokenfactory",
    "contracts/vesting",
    "contracts/vol-earn-vault",
    "contracts/revenue-distributor",
    "contracts/neutron-proxy",
    "contracts/transmuter",
    "contracts/transmuter-lockdrop",
    "contracts/yield-arb",
    "contracts/neutron_launch",
    "contracts/emissions-voting"
]

exclude = [
    "my_scripts", 
    "artifacts", 
    "contracts/cdp/src/testing/*", 
    "contracts/target/*",
    "contracts/managed-market",
    "contracts/market-manager", 
    "contracts/mm-swap",
    "contracts/mm_osmosis_oracle"
]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 'z'
overflow-checks = true
panic = 'abort'
rpath = false

[workspace.dependencies]
base64ct = "=1.7.3"

