[package]
name = "mars-mirror"
version = "0.1.0"
authors = ["Membrane Devs"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = []
library = []

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.13.0
"""

[dependencies]
membrane = { path = "../../packages/membrane" }
cosmwasm-std = { version = "2.0.4", default-features = false, features = ["cosmwasm_2_0", "stargate"] }
cosmwasm-schema = "2.0.4"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
cw2 = "2.0.0"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }

[dev-dependencies]
cosmwasm-schema = "2.0.4"
cw-multi-test = "2.0.0"

