[package]
name = "rps-engine"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.4"
cosmwasm-std = { version = "2.3.0", default-features = false, features = ["cosmwasm_1_1"] }
cw-storage-plus = "1.0.3"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = "1.0"
membrane = { path = "../../packages/membrane" }

[dev-dependencies]
cw-multi-test = "1.0.3"

