[package]
name = "cdp"
version = "0.1.0"
authors = ["Membrane Devs"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = []
# use library feature to disable all instantiate/execute/query exports
library = []


[dependencies]
membrane = { path = "../../packages/membrane" }
osmosis-std = { version = "0.27.0" }
cosmwasm-std = { version = "2.0.4", default-features = false, features = ["cosmwasm_2_0", "stargate"] }
cosmwasm-schema = "2.0.4"
cw-storage-plus = "2.0.0"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }


[dev-dependencies]
cw-multi-test = "2.0.0"
apollo-cw-asset = "0.1.0"
