[package]
name = "racing-revenue"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.4.0"
cosmwasm-std = "1.4.0"
cw-storage-plus = "1.2.0"
cw2 = "1.1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
cw-multi-test = "0.20.0"
